/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
public class Banner extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Banner\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"w\",\"type\":[\"int\",\"null\"]},{\"name\":\"h\",\"type\":[\"int\",\"null\"]},{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"pos\",\"type\":[\"int\",\"null\"]},{\"name\":\"btype\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"battr\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"mimes\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"topframe\",\"type\":[\"int\",\"null\"]},{\"name\":\"expdir\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"api\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public java.lang.Integer w;
  public java.lang.Integer h;
  public java.lang.CharSequence id;
  public java.lang.Integer pos;
  public java.util.List<java.lang.Integer> btype;
  public java.util.List<java.lang.Integer> battr;
  public java.util.List<java.lang.CharSequence> mimes;
  public java.lang.Integer topframe;
  public java.util.List<java.lang.Integer> expdir;
  public java.util.List<java.lang.Integer> api;
  public java.lang.CharSequence ext;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return w;
    case 1: return h;
    case 2: return id;
    case 3: return pos;
    case 4: return btype;
    case 5: return battr;
    case 6: return mimes;
    case 7: return topframe;
    case 8: return expdir;
    case 9: return api;
    case 10: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: w = (java.lang.Integer)value$; break;
    case 1: h = (java.lang.Integer)value$; break;
    case 2: id = (java.lang.CharSequence)value$; break;
    case 3: pos = (java.lang.Integer)value$; break;
    case 4: btype = (java.util.List<java.lang.Integer>)value$; break;
    case 5: battr = (java.util.List<java.lang.Integer>)value$; break;
    case 6: mimes = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: topframe = (java.lang.Integer)value$; break;
    case 8: expdir = (java.util.List<java.lang.Integer>)value$; break;
    case 9: api = (java.util.List<java.lang.Integer>)value$; break;
    case 10: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
