/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
public class Bid extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Bid\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"impid\",\"type\":[\"string\",\"null\"]},{\"name\":\"price\",\"type\":[\"float\",\"null\"]},{\"name\":\"adid\",\"type\":[\"string\",\"null\"]},{\"name\":\"nurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"adm\",\"type\":[\"string\",\"null\"]},{\"name\":\"adomain\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"iurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"cid\",\"type\":[\"string\",\"null\"]},{\"name\":\"crid\",\"type\":[\"string\",\"null\"]},{\"name\":\"attr\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public java.lang.CharSequence id;
  public java.lang.CharSequence impid;
  public java.lang.Float price;
  public java.lang.CharSequence adid;
  public java.lang.CharSequence nurl;
  public java.lang.CharSequence adm;
  public java.util.List<java.lang.CharSequence> adomain;
  public java.lang.CharSequence iurl;
  public java.lang.CharSequence cid;
  public java.lang.CharSequence crid;
  public java.util.List<java.lang.Integer> attr;
  public java.lang.CharSequence ext;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return impid;
    case 2: return price;
    case 3: return adid;
    case 4: return nurl;
    case 5: return adm;
    case 6: return adomain;
    case 7: return iurl;
    case 8: return cid;
    case 9: return crid;
    case 10: return attr;
    case 11: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: impid = (java.lang.CharSequence)value$; break;
    case 2: price = (java.lang.Float)value$; break;
    case 3: adid = (java.lang.CharSequence)value$; break;
    case 4: nurl = (java.lang.CharSequence)value$; break;
    case 5: adm = (java.lang.CharSequence)value$; break;
    case 6: adomain = (java.util.List<java.lang.CharSequence>)value$; break;
    case 7: iurl = (java.lang.CharSequence)value$; break;
    case 8: cid = (java.lang.CharSequence)value$; break;
    case 9: crid = (java.lang.CharSequence)value$; break;
    case 10: attr = (java.util.List<java.lang.Integer>)value$; break;
    case 11: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
