/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
public class BidResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"BidResponse\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"seatbid\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SeatBid\",\"fields\":[{\"name\":\"bid\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Bid\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"impid\",\"type\":[\"string\",\"null\"]},{\"name\":\"price\",\"type\":[\"float\",\"null\"]},{\"name\":\"adid\",\"type\":[\"string\",\"null\"]},{\"name\":\"nurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"adm\",\"type\":[\"string\",\"null\"]},{\"name\":\"adomain\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"iurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"cid\",\"type\":[\"string\",\"null\"]},{\"name\":\"crid\",\"type\":[\"string\",\"null\"]},{\"name\":\"attr\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}}},{\"name\":\"seat\",\"type\":[\"string\",\"null\"]},{\"name\":\"group\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}}},{\"name\":\"bidid\",\"type\":[\"string\",\"null\"]},{\"name\":\"cur\",\"type\":[\"string\",\"null\"]},{\"name\":\"customdata\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public java.lang.CharSequence id;
  public java.util.List<org.openrtb.common.api.SeatBid> seatbid;
  public java.lang.CharSequence bidid;
  public java.lang.CharSequence cur;
  public java.lang.CharSequence customdata;
  public java.lang.CharSequence ext;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return seatbid;
    case 2: return bidid;
    case 3: return cur;
    case 4: return customdata;
    case 5: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: seatbid = (java.util.List<org.openrtb.common.api.SeatBid>)value$; break;
    case 2: bidid = (java.lang.CharSequence)value$; break;
    case 3: cur = (java.lang.CharSequence)value$; break;
    case 4: customdata = (java.lang.CharSequence)value$; break;
    case 5: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
