/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
public class Content extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Content\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"domain\",\"type\":[\"string\",\"null\"]},{\"name\":\"cat\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"sectioncat\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"pagecat\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"version\",\"type\":[\"string\",\"null\"]},{\"name\":\"bundle\",\"type\":[\"string\",\"null\"]},{\"name\":\"privacypolicy\",\"type\":[\"int\",\"null\"]},{\"name\":\"paid\",\"type\":[\"int\",\"null\"]},{\"name\":\"publisher\",\"type\":[{\"type\":\"record\",\"name\":\"Publisher\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"cat\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"domain\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]},\"null\"]},{\"name\":\"content\",\"type\":[\"Content\",\"null\"]},{\"name\":\"keywords\",\"type\":[\"string\",\"null\"]},{\"name\":\"storeurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public java.lang.CharSequence id;
  public java.lang.CharSequence name;
  public java.lang.CharSequence domain;
  public java.util.List<java.lang.CharSequence> cat;
  public java.util.List<java.lang.CharSequence> sectioncat;
  public java.util.List<java.lang.CharSequence> pagecat;
  public java.lang.CharSequence version;
  public java.lang.CharSequence bundle;
  public java.lang.Integer privacypolicy;
  public java.lang.Integer paid;
  public org.openrtb.common.api.Publisher publisher;
  public org.openrtb.common.api.Content content;
  public java.lang.CharSequence keywords;
  public java.lang.CharSequence storeurl;
  public java.lang.CharSequence ext;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return domain;
    case 3: return cat;
    case 4: return sectioncat;
    case 5: return pagecat;
    case 6: return version;
    case 7: return bundle;
    case 8: return privacypolicy;
    case 9: return paid;
    case 10: return publisher;
    case 11: return content;
    case 12: return keywords;
    case 13: return storeurl;
    case 14: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: domain = (java.lang.CharSequence)value$; break;
    case 3: cat = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: sectioncat = (java.util.List<java.lang.CharSequence>)value$; break;
    case 5: pagecat = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: version = (java.lang.CharSequence)value$; break;
    case 7: bundle = (java.lang.CharSequence)value$; break;
    case 8: privacypolicy = (java.lang.Integer)value$; break;
    case 9: paid = (java.lang.Integer)value$; break;
    case 10: publisher = (org.openrtb.common.api.Publisher)value$; break;
    case 11: content = (org.openrtb.common.api.Content)value$; break;
    case 12: keywords = (java.lang.CharSequence)value$; break;
    case 13: storeurl = (java.lang.CharSequence)value$; break;
    case 14: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
