/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.openrtb.common.api;  
@SuppressWarnings("all")
public class Device extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Device\",\"namespace\":\"org.openrtb.common.api\",\"fields\":[{\"name\":\"dnt\",\"type\":[\"int\",\"null\"]},{\"name\":\"ua\",\"type\":[\"string\",\"null\"]},{\"name\":\"ip\",\"type\":[\"string\",\"null\"]},{\"name\":\"geo\",\"type\":[{\"type\":\"record\",\"name\":\"Geo\",\"fields\":[{\"name\":\"lat\",\"type\":[\"float\",\"null\"]},{\"name\":\"lon\",\"type\":[\"float\",\"null\"]},{\"name\":\"country\",\"type\":[\"string\",\"null\"]},{\"name\":\"region\",\"type\":[\"string\",\"null\"]},{\"name\":\"regionfips104\",\"type\":[\"string\",\"null\"]},{\"name\":\"metro\",\"type\":[\"string\",\"null\"]},{\"name\":\"city\",\"type\":[\"string\",\"null\"]},{\"name\":\"zip\",\"type\":[\"string\",\"null\"]},{\"name\":\"type\",\"type\":[\"int\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]},\"null\"]},{\"name\":\"didsha1\",\"type\":[\"string\",\"null\"]},{\"name\":\"didmd5\",\"type\":[\"string\",\"null\"]},{\"name\":\"dpidsha1\",\"type\":[\"string\",\"null\"]},{\"name\":\"dpidmd5\",\"type\":[\"string\",\"null\"]},{\"name\":\"ipv6\",\"type\":[\"string\",\"null\"]},{\"name\":\"carrier\",\"type\":[\"string\",\"null\"]},{\"name\":\"language\",\"type\":[\"string\",\"null\"]},{\"name\":\"make\",\"type\":[\"string\",\"null\"]},{\"name\":\"model\",\"type\":[\"string\",\"null\"]},{\"name\":\"os\",\"type\":[\"string\",\"null\"]},{\"name\":\"Osv\",\"type\":[\"string\",\"null\"]},{\"name\":\"Js\",\"type\":[\"int\",\"null\"]},{\"name\":\"connectiontype\",\"type\":[\"int\",\"null\"]},{\"name\":\"deviceType\",\"type\":[\"int\",\"null\"]},{\"name\":\"flashver\",\"type\":[\"string\",\"null\"]},{\"name\":\"ext\",\"type\":[\"string\",\"null\"]}]}");
  public java.lang.Integer dnt;
  public java.lang.CharSequence ua;
  public java.lang.CharSequence ip;
  public org.openrtb.common.api.Geo geo;
  public java.lang.CharSequence didsha1;
  public java.lang.CharSequence didmd5;
  public java.lang.CharSequence dpidsha1;
  public java.lang.CharSequence dpidmd5;
  public java.lang.CharSequence ipv6;
  public java.lang.CharSequence carrier;
  public java.lang.CharSequence language;
  public java.lang.CharSequence make;
  public java.lang.CharSequence model;
  public java.lang.CharSequence os;
  public java.lang.CharSequence Osv;
  public java.lang.Integer Js;
  public java.lang.Integer connectiontype;
  public java.lang.Integer deviceType;
  public java.lang.CharSequence flashver;
  public java.lang.CharSequence ext;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return dnt;
    case 1: return ua;
    case 2: return ip;
    case 3: return geo;
    case 4: return didsha1;
    case 5: return didmd5;
    case 6: return dpidsha1;
    case 7: return dpidmd5;
    case 8: return ipv6;
    case 9: return carrier;
    case 10: return language;
    case 11: return make;
    case 12: return model;
    case 13: return os;
    case 14: return Osv;
    case 15: return Js;
    case 16: return connectiontype;
    case 17: return deviceType;
    case 18: return flashver;
    case 19: return ext;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: dnt = (java.lang.Integer)value$; break;
    case 1: ua = (java.lang.CharSequence)value$; break;
    case 2: ip = (java.lang.CharSequence)value$; break;
    case 3: geo = (org.openrtb.common.api.Geo)value$; break;
    case 4: didsha1 = (java.lang.CharSequence)value$; break;
    case 5: didmd5 = (java.lang.CharSequence)value$; break;
    case 6: dpidsha1 = (java.lang.CharSequence)value$; break;
    case 7: dpidmd5 = (java.lang.CharSequence)value$; break;
    case 8: ipv6 = (java.lang.CharSequence)value$; break;
    case 9: carrier = (java.lang.CharSequence)value$; break;
    case 10: language = (java.lang.CharSequence)value$; break;
    case 11: make = (java.lang.CharSequence)value$; break;
    case 12: model = (java.lang.CharSequence)value$; break;
    case 13: os = (java.lang.CharSequence)value$; break;
    case 14: Osv = (java.lang.CharSequence)value$; break;
    case 15: Js = (java.lang.Integer)value$; break;
    case 16: connectiontype = (java.lang.Integer)value$; break;
    case 17: deviceType = (java.lang.Integer)value$; break;
    case 18: flashver = (java.lang.CharSequence)value$; break;
    case 19: ext = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
